src/Entity/Question.php
<?php

namespace App\Entity;

use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=QuestionRepository::class)
 */
class Question
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $posted_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $resolve;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="questions")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Answer::class, mappedBy="question", orphanRemoval=true)
     */
    private $answers;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="question")
     */
    private $comments;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, mappedBy="questions")
     */
    private $tags;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    public function __construct()
    {
        $this->answers = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getPostedAt(): ?\DateTimeImmutable
    {
        return $this->posted_at;
    }

    public function setPostedAt(\DateTimeImmutable $posted_at): self
    {
        $this->posted_at = $posted_at;

        return $this;
    }

    public function getResolve(): ?bool
    {
        return $this->resolve;
    }

    public function setResolve(bool $resolve): self
    {
        $this->resolve = $resolve;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection|Answer[]
     */
    public function getAnswers(): Collection
    {
        return $this->answers;
    }

    public function addAnswer(Answer $answer): self
    {
        if (!$this->answers->contains($answer)) {
            $this->answers[] = $answer;
            $answer->setQuestion($this);
        }

        return $this;
    }

    public function removeAnswer(Answer $answer): self
    {
        if ($this->answers->removeElement($answer)) {
            // set the owning side to null (unless already changed)
            if ($answer->getQuestion() === $this) {
                $answer->setQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setQuestion($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getQuestion() === $this) {
                $comment->setQuestion(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addQuestion($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeQuestion($this);
        }

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }
}

src/Form/Type/QuestionType.php
<?php

namespace App\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Form\Type\TagType;
use App\Entity\Question;

class QuestionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
				'label'  => 'Intitulé',
			])
            ->add('content', TextareaType::class, [
				'label'  => 'Votre question',
			])
            ->add('tags', CollectionType::class, [
				'label'  => 'Tags',
				'entry_type' => TagType::class,
				'prototype' => true,
				'allow_add' => true,
				'by_reference' => false,
				'entry_options' => [
					'attr' => ['class' => 'tag-box'],
				],
			])
            ->add('submit', SubmitType::class, [
				'label'  => 'Sauvegarder',
			])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Question::class,
        ]);
    }
}

?>

src/Controller/QuestionController.php
<?php
namespace App\Controller;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Entity\Question;
use App\Entity\Answer;
use App\Entity\Tag;
use App\Entity\Comment;
use App\Entity\UserVoteAnswer;
use App\Form\Type\QuestionType;
use App\Form\Type\AnswerType;
use App\Form\Type\CommentType;

class QuestionController extends AbstractController
{
	
	public function postQuestion(Request $request): Response
	{
		$question = new Question();

        $form = $this->createForm(QuestionType::class, $question, [
            'action' => $this->generateUrl('post_question'),
            'method' => 'POST',
        ]);
		
		$form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
			
            $question = $form->getData();
			$question->setPostedAt(new \DatetimeImmutable());
			$question->setUser($this->getUser());
			$question->setSlug(str_replace(' ', '-', $question->getTitle()));
			$question->setResolve(false);
			
			$repository = $this->getDoctrine()->getRepository(Tag::class);
            $entityManager = $this->getDoctrine()->getManager();
			
			foreach($question->getTags() as $tag){
				
				$tag->addQuestion($question);
				$question->addTag($tag);
				$entityManager->persist($tag);
				
			}
			
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('subject', array(
				'id' => $question->getId(),
				'slug' => $question->getSlug(),
			));
        }

        return $this->render('Question/post_question.html.twig', [
            'form' => $form->createView(),
        ]);
		
	}
	
	public function postAnswer(Request $request, string $slug, int $id): Response
	{
		$answer = new Answer();

        $form = $this->createForm(AnswerType::class, $answer, [
            'action' => $this->generateUrl('post_answer', array(
				'slug' => $slug,
			)),
            'method' => 'POST',
        ]);
		
		$form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $answer = $form->getData();
			$repository = $this->getDoctrine()->getRepository(Question::class);
			$question = $repository->findOneBySlugAndId($id, $slug);
			$answer->setUser($this->getUser());
			$question->addAnswer($answer);
			$answer->setVote(0);
			$answer->setPostedAt(new \DatetimeImmutable());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($answer);
            $entityManager->flush();

            return $this->redirectToRoute('subject', array(
				'id' => $question->getId(),
				'slug' => $question->getSlug(),
			));
			
        }

        return $this->render('Question/post_answer.html.twig', [
            'form' => $form->createView(),
        ]);
	}
	
	public function postCommentQuestion(Request $request, string $slug, int $id): Response
	{
		$comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment, [
            'action' => $this->generateUrl('post_comment_question', array(
				'slug' => $slug,
			)),
            'method' => 'POST',
        ]);
		
		$form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment = $form->getData();
			$repository = $this->getDoctrine()->getRepository(Question::class);
			$question = $repository->findOneBySlugAndId($id, $slug);
			$comment->setUser($this->getUser());
			$question->addComment($comment);
			$comment->setPostedAt(new \DatetimeImmutable());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('subject', array(
				'id' => $question->getId(),
				'slug' => $question->getSlug(),
			));
        }

        return $this->render('Question/post_answer.html.twig', [
            'form' => $form->createView(),
        ]);
		
	}
	
	public function postCommentAnswer(Request $request, int $id): Response
	{
		$comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment, [
            'action' => $this->generateUrl('post_comment_answer', array(
				'id' => $id,
			)),
            'method' => 'POST',
        ]);
		
		$form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $comment = $form->getData();
			$repository = $this->getDoctrine()->getRepository(Answer::class);
			$answer = $repository->find($id);
			$comment->setUser($this->getUser());
			$answer->addComment($comment);
			$comment->setPostedAt(new \DatetimeImmutable());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('subject', array(
				'id' => $question->getId(),
				'slug' => $answer->getQuestion()->getSlug(),
			));
        }

        return $this->render('Question/post_answer.html.twig', [
            'form' => $form->createView(),
        ]);
		
	}
	
	public function subject(int $id, string $slug): Response
	{
		$repository = $this->getDoctrine()->getRepository(Question::class);
		$question = $repository->findOneBySlugAndId($id, $slug);

        return $this->render('Question/subject.html.twig', [
            'question' => $question,
        ]);
		
	}
	
	public function resolve(string $slug, int $id): Response
	{
		$repository = $this->getDoctrine()->getRepository(Question::class);
		$question = $repository->findOneBySlugAndId($id, $slug);
		$question->setResolve(true);
		$this->getDoctrine()->getManager()->flush();

		return $this->redirectToRoute('subject', array(
			'id' => $question->getId(),
			'slug' => $question->getSlug(),
		));
		
	}
	
	public function vote(int $id, int $value): Response
	{
		
		$repository = $this->getDoctrine()->getRepository(UserVoteAnswer::class);
		$userVoteAnswer = $repository->findOneBy(array('user' => $this->getUser(), 'answer' => $id));
		$repository = $this->getDoctrine()->getRepository(Answer::class);
		$answer = $repository->find($id);
		if($userVoteAnswer == null)
		{
			$answer->setVote($answer->getVote() + $value);
			$userVoteAnswer = new UserVoteAnswer();
			$userVoteAnswer->setUser($this->getUser());
			$userVoteAnswer->setAnswer($answer);
			$userVoteAnswer->setVote(true);
			$manager = $this->getDoctrine()->getManager();
			$manager->persist($userVoteAnswer);
			$manager->flush();
		}

		return $this->redirectToRoute('subject', array(
			'id' => $question->getId(),
			'slug' => $answer->getQuestion()->getSlug(),
		));
		
	}
	
}

templates/Question/post_answer.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('css/post_answer.css') }}">
{% endblock %}

{% block body %}

	{{ form_start(form) }}
		<div class="row">
			<div class="col">
				{{ form_errors(form.content) }}
				<div  class="form-label">{{ form_label(form.content) }}</div>
				<div  class="form-control">{{ form_widget(form.content) }}</div>
			</div>
		</div>
	{{ form_end(form) }}

{% endblock %}

templates/Question/post_question.html.twig
{% extends 'base.html.twig' %}

{% block title %}Poser une question{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('css/post_question.css') }}">
{% endblock %}

{% block body %}

	{{ form_start(form) }}

		<div class="row">
			<div class="col-md-5">
				{{ form_errors(form.title) }}
				<div  class="form-label">{{ form_label(form.title) }}</div>
				<div  class="form-control">{{ form_widget(form.title) }}</div>
			</div>
			<ul class="col-md-7 tags" data-prototype="{{ form_widget(form.tags.vars.prototype)|e('html_attr') }}">
				{{ form_label(form.tags) }}
				{% for tag in form.tags %}
					<li>
						{{ form_errors(tag) }}
						{{ form_widget(tag) }}
					</li>
				{% endfor %}
				<button type="button" class="add_item_link" data-collection-holder-class="tags">Ajouter un tag</button>
			</ul>
		</div>
		<div class="row">
			<div class="col">
				{{ form_errors(form.content) }}
				<div  class="form-label">{{ form_label(form.content) }}</div>
				<div  class="form-control">{{ form_widget(form.content) }}</div>
			</div>
		</div>
	{{ form_end(form) }}

{% endblock %}

{% block javascripts %}

	{{ parent() }}
	<script type="text/javascript">
		var $addTagLink = $('.add_item_link');
		var $newLinkLi = $('<li></li>');

		jQuery(document).ready(function() {
		   var $collectionHolder = $('ul.tags');
			
			$collectionHolder.append($newLinkLi);
			
			$collectionHolder.data('index', $collectionHolder.find(':input').length);
			
			$addTagLink.on('click', function(e) {
				e.preventDefault();
				addTagForm($collectionHolder, $newLinkLi);
			});
			
			
		});
			
		function addTagForm($collectionHolder, $newLinkLi) {
			var prototype = $collectionHolder.data('prototype');
			
			var index = $collectionHolder.data('index');
			
			var newForm = prototype.replace(/__name__/g, index);
			
			$collectionHolder.data('index', index + 1);
			
			var $newFormLi = $('<li></li>').append(newForm);
			
			$newFormLi.append('<a href="#" class="remove-tag">x</a>');
			
			$newLinkLi.before($newFormLi);
			
			$('.remove-tag').click(function(e) {
				e.preventDefault();
				
				$(this).parent().remove();
				
				return false;
			});
		}
	</script>
	
{% endblock %}

templates/Question/subject.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block stylesheets %}
	{{ parent() }}
	<link rel="stylesheet" href="{{ asset('css/subject.css') }}">
{% endblock %}

{% block body %}

	<h1>{{ question.title }}</h1>
	<br/>
	<p>Tag : 
		{% if question.tags is defined and question.tags is not null %}
		
			{% for tag in question.tags %}
			
				{{ tag.title }} 
			
			{% endfor %}
		
		{% endif %}
	<p> Par {{ question.user.pseudo }} le {{ question.postedAt|date("d/m/Y") }}</p>
	<br/>
	<p>{{ question.content }}</p>
	{% if is_granted('ROLE_USER') %}<a href="{{ path('post_comment_question', { slug: question.slug, id: question.id}) }}">Poster un commentaire</a>{% endif %}
	{% if app.user.id is same as (question.user.id) and question.resolve is same as(false) %}
		<a href="{{ path('resolve', { slug: question.slug, id: question.id}) }}">Résolue</a>
	{% endif %}
	<hr>
	{% if question.comments is defined and question.comments is not null %}
		{% for comment in question.comments %}
		
			<p>{{ comment.user.pseudo }} le {{ comment.postedAt|date("d/m/Y") }}</p>
			<p>{{ comment.content }}
			<hr>
		
		{% endfor %}
	{% endif %}
	
	<br/>
	{% is_granted('ROLE_USER') %}<a href="{{ path('post_answer', { slug: question.slug, id: question.id}) }}">Poster une réponse</a>{% endif %}
	
	{% if question.answers is defined and question.answers is not null %}
		{% for answer in question.answers %}
			<h3>Par {{ answer.user.pseudo }} le {{ answer.postedAt|date("d/m/Y") }}</h3>
			<p>{{ answer.vote }} {% if answer.userVoteAnswer is defined and answer.userVoteAnswer is not null and answer.userVoteAnswer.vote is same as (true) %} Vous avez déjà voté {% else %}<a href="{{ path('vote', {id: answer.id, value: -1} )}}">-</a> <a href="{{ path('vote', {id: answer.id, value: 1} )}}">+</a> {% endif %}</p>
			<p>{{ answer.content }}</p>
			{% is_granted('ROLE_USER') %}<a href="{{ path('post_comment_answer', { id: answer.id}) }}">Poster un commentaire</a>{% endif %}
			<hr>
			{% if answer.comments is defined and answer.comments is not null %}
				{% for comment in answer.comments %}
		
					<p>{{ comment.user.pseudo }} le {{ comment.postedAt|date("d/m/Y") }}</p>
					<p>{{ comment.content }}
					<hr>
				
				{% endfor %}
			{% endif %}
			<br/>
			<br/>
			<br/>
		{% endfor %}
	{% endif %}
{% endblock %}